spring:
  h2:
    console:
      enabled: true
      path: '/db'
  datasource:
    url: 'jdbc:h2:file:/Users/bartekmacbook/Desktop/CarSharing-App/app-db'
    driverClassName: org.h2.Driver
    username: 'sa'
    password:
  main:
    banner-mode: off
car:
  rent-multiple-cars: false
  security:
    username: 'tomek'
    password: 'atomek'
  admin:
    online: false
