spring:
  h2:
    console:
      enabled: true
      path: '/db'
  datasource:
    url: 'jdbc:h2:file:C:\Users\Bartek\Desktop\RentCar\car-db'
    driverClassName: org.h2.Driver
    username: 'sa'
    password:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: create-drop
car:
  rent-multiple-cars: false
  security:
    username: 'tomek'
    password: 'atomek'
  admin:
    online: false
